"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

load_dotenv()

# Vrai pendant `manage.py test` : sert à neutraliser le throttling de login,
# sinon les nombreuses connexions de la suite de tests (même IP) déclencheraient
# le 429. Le comportement du throttle est vérifié à part via override_settings.
TESTING = 'test' in sys.argv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Piloté par l'environnement, avec False par défaut : si la variable est
# absente ou mal orthographiée en production, on reste en mode sûr.
# Calculé AVANT SECRET_KEY : le comportement de repli de la clé en dépend.
DEBUG = os.environ.get('DEBUG', 'False').strip().lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
# En production (DEBUG=False), la variable SECRET_KEY est OBLIGATOIRE : on
# échoue au démarrage plutôt que de tourner avec une clé triviale. En dev, un
# repli local suffit pour ne pas bloquer le développement.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-not-for-production'
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "La variable d'environnement SECRET_KEY est absente. Elle est "
            "obligatoire en production : définissez-la sur l'hébergeur "
            "(Railway) avant de démarrer l'application."
        )

# Hôtes autorisés : liste explicite (anti Host-header injection), pilotée par
# l'environnement pour ne pas casser le développement local. En local, DEBUG
# vaut False par défaut, d'où localhost/127.0.0.1 dans la liste par défaut.
_DEFAULT_ALLOWED_HOSTS = (
    'urbanflow-mobility-production.up.railway.app,localhost,127.0.0.1'
)
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', _DEFAULT_ALLOWED_HOSTS).split(',')
    if host.strip()
]

# Railway injecte le domaine public réel : on l'ajoute automatiquement, ce qui
# évite un 400 DisallowedHost si le sous-domaine change.
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # Local
    'users',
    'routing',
    'transport',
    'carbon',
    'incidents',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Sélection de la base, par ordre de priorité :
#   1. DATABASE_URL  — variable standard fournie par Railway, Heroku, etc.
#                      C'est celle qu'injecte le service PostgreSQL de Railway.
#   2. variables PG* séparées — utile si on les définit à la main.
#   3. SQLite — uniquement pour le développement local.
#
# Attention : sur Railway, SQLite vit sur un disque éphémère. Toute donnée
# écrite dedans disparaît au redéploiement suivant, d'où l'avertissement
# explicite plus bas si on y retombe hors DEBUG.
if os.environ.get('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,  # connexions persistantes
        )
    }
    DATABASE_SOURCE = 'DATABASE_URL'
elif os.environ.get('PGDATABASE'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PGDATABASE'),
            'USER': os.environ.get('PGUSER'),
            'PASSWORD': os.environ.get('PGPASSWORD'),
            'HOST': os.environ.get('PGHOST'),
            'PORT': os.environ.get('PGPORT', '5432'),
            'CONN_MAX_AGE': 600,
        }
    }
    DATABASE_SOURCE = 'variables PG*'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    DATABASE_SOURCE = 'SQLite (local)'

    if not DEBUG:
        # En production, retomber sur SQLite signifie perdre toutes les
        # données au prochain déploiement. On le signale très visiblement
        # dans les logs plutôt que de le laisser passer inaperçu.
        import sys

        print(
            '\n'
            '========================================================\n'
            'ALERTE : aucune base PostgreSQL configurée en production.\n'
            'Django utilise SQLite sur un disque ÉPHÉMÈRE : toutes les\n'
            'données seront perdues au prochain déploiement.\n'
            "Définissez DATABASE_URL (ou les variables PG*) sur l'hébergeur.\n"
            '========================================================\n',
            file=sys.stderr,
            flush=True,
        )

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Custom user model : Django doit utiliser notre modèle User (email comme identifiant)
# au lieu du modèle par défaut. À déclarer AVANT la première migration.
AUTH_USER_MODEL = 'users.User'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Durée de vie des tokens de réinitialisation de mot de passe : 30 minutes.
PASSWORD_RESET_TIMEOUT = 30 * 60

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenRouteService : clé lue depuis le .env, jamais exposée au frontend.
ORS_API_KEY = os.environ.get('ORS_API_KEY', '')

# APIs de transport (Sprint 3). Comme ORS, ces clés restent côté serveur :
# le frontend passe toujours par nos propres endpoints.
JCDECAUX_API_KEY = os.environ.get('JCDECAUX_API_KEY', '')
VELIB_PRIM_API_KEY = os.environ.get('VELIB_PRIM_API_KEY', '')
OWMAP_API_KEY = os.environ.get('OWMAP_API_KEY', '')

# Cache mémoire pour amortir les appels aux APIs externes (TTL de 60 s défini
# dans transport/services/base.py). Local au processus : avec plusieurs
# workers gunicorn, chacun a le sien — acceptable pour une durée aussi courte.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'urbanflow-transport',
    }
}

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://urbanflow-mobility.up.railway.app",
]

# CSRF derrière le proxy Railway.
# Le domaine du backend doit être déclaré comme origine de confiance, sinon
# le POST de connexion à l'admin échoue en « CSRF verification failed ».
CSRF_TRUSTED_ORIGINS = ["https://urbanflow-mobility-production.up.railway.app"]

# Railway termine le TLS en amont et transmet la requête en HTTP interne :
# sans cet en-tête, Django la croit non sécurisée et rejette le cookie CSRF.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Durcissement des en-têtes de sécurité (NF2 / OWASP), activé UNIQUEMENT hors
# DEBUG : en local on tourne en HTTP simple, ces réglages provoqueraient des
# redirections HTTPS et des cookies « Secure » inutilisables sans TLS.
if not DEBUG:
    # Force la redirection HTTP -> HTTPS. Pas de boucle de redirection : le
    # SECURE_PROXY_SSL_HEADER ci-dessus indique déjà à Django que la requête
    # d'origine est bien en HTTPS (TLS terminé par le proxy Railway).
    SECURE_SSL_REDIRECT = True
    # Cookies de session et CSRF transmis uniquement via HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS : impose HTTPS pour un an, sous-domaines inclus, éligible au preload.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Fail-safe : par défaut, tout endpoint exige une authentification. Les vues
    # publiques par conception (login, register, GET signalements, reset mot de
    # passe) déclarent explicitement AllowAny / IsAuthenticatedOrReadOnly et ne
    # sont donc pas affectées. Une future vue qui oublierait ses permissions
    # sera fermée par défaut plutôt qu'ouverte.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Limitation anti brute-force : la vue de login (scope « login ») est
    # plafonnée à 5 tentatives par minute et par IP. Le compteur s'appuie sur
    # le cache par défaut (LocMemCache) — par process gunicorn, donc à multiplier
    # par le nombre de workers, ce qui reste protecteur pour ce prototype.
    'DEFAULT_THROTTLE_RATES': {
        # Désactivé pendant la suite de tests (None), 5/min/IP en usage réel.
        'login': None if TESTING else '5/min',
    },
}