# Generated by Django 4.2.30 on 2026-07-18 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(verbose_name='distance parcourue (km)')),
                ('co2_emis', models.FloatField(verbose_name='CO₂ émis (g)')),
                ('co2_economise', models.FloatField(verbose_name='CO₂ économisé vs voiture (g)')),
                ('date_trajet', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date du trajet')),
                ('modes_utilises', models.JSONField(default=list, verbose_name='modes utilisés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trajet',
                'verbose_name_plural': 'trajets',
                'ordering': ['-date_trajet'],
                'indexes': [models.Index(fields=['user', '-date_trajet'], name='carbon_traj_user_id_3b486a_idx')],
            },
        ),
    ]
