# Generated by Django 4.2.30 on 2026-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='arrivee',
            field=models.CharField(blank=True, max_length=255, verbose_name="point d'arrivée"),
        ),
        migrations.AddField(
            model_name='trajet',
            name='depart',
            field=models.CharField(blank=True, max_length=255, verbose_name='point de départ'),
        ),
    ]
