# Generated by Django 4.2.30 on 2026-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0002_trajet_arrivee_trajet_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='duree_s',
            field=models.PositiveIntegerField(default=0, verbose_name='durée du trajet (s)'),
        ),
    ]
