# Generated by Django 4.2.30 on 2026-07-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('travaux', 'Travaux'), ('accident', 'Accident'), ('panne', 'Panne'), ('autre', 'Autre')], max_length=20, verbose_name="type d'incident")),
                ('commentaire', models.TextField(blank=True, max_length=500, verbose_name='commentaire')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date du signalement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'ordering': ['-date_signalement'],
                'indexes': [models.Index(fields=['-date_signalement'], name='incidents_i_date_si_b05a1d_idx')],
            },
        ),
    ]
