# Generated by Django 4.2.30 on 2026-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_test_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('resolu', 'Résolu'), ('expire', 'Expiré')], default='actif', max_length=20, verbose_name='statut'),
        ),
    ]
