# Generated by Django 4.2.30 on 2026-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='votes'),
        ),
    ]
