# Generated by Django 4.2.30 on 2026-08-25 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0005_rename_incident_signalement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_creation'], 'verbose_name': 'signalement', 'verbose_name_plural': 'signalements'},
        ),
        migrations.RemoveIndex(
            model_name='signalement',
            name='incidents_i_date_si_b05a1d_idx',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['-date_creation'], name='incidents_s_date_cr_66ef45_idx'),
        ),
    ]
